datacity_public_homepage:
    pattern:  /
    defaults: { _controller: DatacityPublicBundle:Page:home }

datacity_public_partials:
    pattern:  /partials/{pageName}
    defaults: { _controller: DatacityPublicBundle:Page:partials }
    requirements:
        pageName:  \w+

datacity_public_contactpage:
    pattern:  /contact
    defaults: { _controller: DatacityPublicBundle:Page:contact }

datacity_public_portalpage:
    pattern:  /app
    defaults: { _controller: DatacityPublicBundle:App:portal }

datacity_public_appDetail:
    pattern:  /app/{id}
    defaults: { _controller: DatacityPublicBundle:App:appDetail, id: 0 }
    
datacity_public_news:
    pattern:  /news
    defaults: { _controller: DatacityPublicBundle:News:news }
   
datacity_public_newsDetail:
    pattern:  /news/{id}
    defaults: { _controller: DatacityPublicBundle:News:newsDetail, id: 0 }

datacity_public_dataviewpage:
    pattern:  /dataview
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'DatacityPublicBundle::dataview.html.twig'

datacity_public_api_search:
    pattern:  /api/search
    defaults: { _controller: DatacityPublicBundle:SearchApi:search }
    options:
        expose: true

datacity_public_api_place:
    pattern:  /api/place
    defaults: { _controller: DatacityPublicBundle:SearchApi:place }
    options:
        expose: true

datacity_public_api_search_list:
    pattern:  /api/searchlistfilter
    defaults: { _controller: DatacityPublicBundle:SearchApi:searchListFilter }
    options:
        expose: true

datacity_public_api_search_popular:
    pattern:  /api/popular
    defaults: { _controller: DatacityPublicBundle:SearchApi:popular }
    options:
        expose: true

datacity_public_api_dataset_show:
    pattern:  /api/dataset/{slug}
    defaults: { _controller: DatacityPublicBundle:DatasetApi:show }
    options:
        expose: true

datacity_public_condition:
    pattern:  /condition
    defaults: { _controller: DatacityPublicBundle:Page:condition }

datacity_public_privacypolicy:
    pattern:  /privacypolicy
    defaults: { _controller: DatacityPublicBundle:Page:privacypolicy }

