datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_dashboard:
    pattern:  /dashboard
    defaults: { _controller: DatacityPrivateBundle:Dashboard:index }
