datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_dashboard:
    pattern:  /dashboard
    defaults: { _controller: DatacityPrivateBundle:Dashboard:index }

datacity_private_usersmanager:
    pattern:  /usersmanager
    defaults: { _controller: DatacityPrivateBundle:UsersManager:index }

datacity_private_usersmanager_remove:
    pattern:  /usersmanager/remove/{user_id}
    defaults: { _controller: DatacityPrivateBundle:UsersManager:remove, user_id: -1 }

datacity_private_news:
    pattern:  /news
    defaults: { _controller: DatacityPrivateBundle:News:index }

datacity_private_news_add:
    pattern:  /news/add
    defaults: { _controller: DatacityPrivateBundle:News:add }

datacity_private_news_remove:
    pattern:  /news/remove/{news_id}
    defaults: { _controller: DatacityPrivateBundle:News:remove, news_id: -1 }

datacity_private_profilemanager:
    pattern:  /profilemanager
    defaults: { _controller: DatacityPrivateBundle:ProfileManager:index }

datacity_private_partials:
    pattern:  /partials/{pageName}
    defaults: { _controller: DatacityPrivateBundle:Default:partials }

datacity_private_modals:
    pattern: /modals/{pageName}
    defaults: { _controller: DatacityPrivateBundle:Default:modals }

datacity_private_datasetmanager_delete:
    pattern: /dataset/delete/{id}
    defaults: { _controller: DatacityPrivateBundle:DataSet:delete }

datacity_private_datasetmanager_save:
    pattern: /dataset/save/
    defaults: { _controller: DatacityPrivateBundle:DataSet:save }

datacity_private_datasetmanager_get:
    pattern: /dataset/get/{id}
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }

datacity_private_usermanager_get:
    pattern: /user/get
    defaults: { _controller: DatacityPrivateBundle:UserManager:get }
    options:
        expose: true

datacity_private_usermanager_post:
    pattern: /user/post
    defaults: { _controller: DatacityPrivateBundle:UserManager:post }
    options:
        expose: true

datacity_private_usermanager_uploadimage:
    pattern: /user/uploadimage
    defaults: { _controller: DatacityPrivateBundle:UserManager:uploadimage }
    options:
        expose: true

datacity_private_usermanager_updatepassword:
    pattern: /user/changepassword
    defaults: { _controller: DatacityPrivateBundle:UserManager:updatepassword }
    options:
        expose: true