datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_dashboard:
    pattern:  /dashboard
    defaults: { _controller: DatacityPrivateBundle:Dashboard:index }

datacity_private_usersmanager:
    pattern:  /usersmanager
    defaults: { _controller: DatacityPrivateBundle:UsersManager:index }

datacity_private_usersmanager_remove:
    pattern:  /usersmanager/remove/{user_id}
    defaults: { _controller: DatacityPrivateBundle:UsersManager:remove, user_id: -1 }

datacity_private_news:
    pattern:  /news
    defaults: { _controller: DatacityPrivateBundle:News:index }

datacity_private_news_add:
    pattern:  /news/add
    defaults: { _controller: DatacityPrivateBundle:News:add }

datacity_private_news_remove:
    pattern:  /news/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:News:remove }
    options:
        expose: true

datacity_private_profilemanager:
    pattern:  /profilemanager
    defaults: { _controller: DatacityPrivateBundle:ProfileManager:index }

datacity_private_partials:
    pattern:  /partials/{pageName}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:Default:partials }

datacity_private_modals:
    pattern: /modals/{pageName}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:Default:modals }

datacity_private_dataset_delete:
    pattern: /dataset/{id}
    requirements:
        _method:  DELETE
    defaults: { _controller: DatacityPrivateBundle:DataSet:delete }

datacity_private_dataset_save:
    pattern: /dataset/
    requirements:
        _method:  POST
    defaults: { _controller: DatacityPrivateBundle:DataSet:save }

datacity_private_dataset_get:
    pattern: /dataset/{slug}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }

datacity_private_source_post:
    pattern: /dataset/{slug}/source/
    requirements:
        _method: POST
    defaults: { _controller: DatacityPrivateBundle:Source:save }
    options:
        expose: true

datacity_private_usermanager_get:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:UserManager:get }
    requirements:
        _method:  GET
    options:
        expose: true

datacity_private_usermanager_post:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:UserManager:post }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_usermanager_uploadimage:
    pattern: /user/uploadimage
    defaults: { _controller: DatacityPrivateBundle:UserManager:uploadimage }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_usermanager_updatepassword:
    pattern: /user/changepassword
    defaults: { _controller: DatacityPrivateBundle:UserManager:updatepassword }
    requirements:
        _method:  POST
    options:
        expose: true