datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_adminusers:
    pattern:  /users
    defaults: { _controller: DatacityPrivateBundle:AdminUsers:index }

datacity_private_adminusers_remove:
    pattern:  /users/{usernameCanonical}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:AdminUsers:remove }
    options:
        expose: true

datacity_private_adminusers_edit:
    pattern: /users/{firstname}
    defaults: {_controller: DatacityPrivateBundle:AdminUsers:edit}
    options:
        expose: true

datacity_private_news:
    pattern:  /news
    defaults: { _controller: DatacityPrivateBundle:News:index }

datacity_private_news_edit:
    pattern:  /news/edit/{title}
    defaults: { _controller: DatacityPrivateBundle:News:edit }

datacity_private_news_add:
    pattern:  /news/add
    requirements:
        _method: GET|POST
    defaults: { _controller: DatacityPrivateBundle:News:add }

datacity_private_news_remove:
    pattern:  /news/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:News:remove }
    options:
        expose: true

datacity_private_partials:
    pattern:  /partials
    requirements:
        _method:  GET
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'DatacityPrivateBundle:Partials:appTemplate.html.twig'
    options:
        expose: true

datacity_private_modals:
    pattern: /modals/{pageName}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:Default:modals }

datacity_private_dataset_delete:
    pattern: /dataset/{id}
    requirements:
        _method:  DELETE
    defaults: { _controller: DatacityPrivateBundle:DataSet:delete }

datacity_private_dataset_save:
    pattern: /dataset/
    requirements:
        _method:  POST
    defaults: { _controller: DatacityPrivateBundle:DataSet:save }
    options:
        expose: true

datacity_private_dataset_get:
    pattern: /dataset/{offset}
    requirements:
        _method:  GET
        offset: \d+
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }
    options:
        expose: true

datacity_private_dataset_get:
    pattern: /dataset/{slug}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }

datacity_private_source_post:
    pattern: /dataset/{slug}/source/
    requirements:
        _method: POST
    defaults: { _controller: DatacityPrivateBundle:Source:save }
    options:
        expose: true

datacity_private_producers_get:
    pattern: /producers
    defaults: { _controller: DatacityPrivateBundle:Producers:get }
    requirements:
        _method:  GET
    options:
        expose: true

datacity_private_producers_edit:
    pattern: /producers/edit/{name}
    defaults: {_controller: DatacityPrivateBundle:Producers:edit}
    options:
        expose: true

datacity_private_producer_remove:
    pattern:  /producers/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:Producers:remove }
    options:
        expose: true

datacity_private_producers_post:
    pattern: /producers/add
    defaults: { _controller: DatacityPrivateBundle:Producers:post }
    requirements:
        _method:  GET|POST

datacity_private_producers_list:
    pattern: /producers/list
    defaults: { _controller: DatacityPrivateBundle:Producers:list }

datacity_private_user_get:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:User:get }
    requirements:
        _method:  GET
    options:
        expose: true

datacity_private_user_post:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:User:post }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_user_uploadimage:
    pattern: /user/uploadimage
    defaults: { _controller: DatacityPrivateBundle:User:uploadimage }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_user_updatepassword:
    pattern: /user/changepassword
    defaults: { _controller: DatacityPrivateBundle:User:updatepassword }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_applications_list:
    pattern: /applications/list
    defaults: {_controller: DatacityPrivateBundle:Applications:list}

datacity_private_applications_post:
    pattern: /applications/add
    defaults: {_controller: DatacityPrivateBundle:Applications:post}

datacity_private_tickets_list:
    pattern: /tickets
    defaults: {_controller: DatacityPrivateBundle:Tickets:index}

datacity_private_ticket_remove:
    pattern:  /tickets/{title}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:Tickets:remove }
    options:
        expose: true

datacity_public_ticket_detail_admin:
    pattern:  /ticket/{slug}
    defaults: { _controller: DatacityPrivateBundle:Tickets:ticketDetailAdmin, slug: ""}

datacity_private_tickets_post:
    pattern: /ticket/{slug}
    defaults: { _controller: DatacityPrivateBundle:Tickets:post }
    requirements:
        _method:  POST


datacity_private_applications_edit:
    pattern: /applications/edit/{name}
    defaults: {_controller: DatacityPrivateBundle:Applications:edit}
    options:
        expose: true

datacity_private_applications_remove:
    pattern:  /applications/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:Applications:remove }
    options:
        expose: true

datacity_private_applications_get_userapplications:
    pattern: /applications/userapps
    defaults: {_controller: DatacityPrivateBundle:Applications:getuserapplications}
    options:
        expose: true

datacity_private_applications_get_application:
    pattern: /application/edit/{slug}
    defaults: {_controller: DatacityPrivateBundle:Applications:getapp}
    options:
        expose: true

datacity_private_applications_get_app_data:
    pattern: /application/getappdata
    defaults: {_controller: DatacityPrivateBundle:Applications:getappdata}
    options:
        expose: true

datacity_private_applications_post_user_app:
    pattern: /application/postuserapp
    requirements:
        _method:  POST
    defaults: {_controller: DatacityPrivateBundle:Applications:postuserapp}
    options:
        expose: true

datacity_private_applications_delete_user_app:
    pattern: /application/deleteuserapp
    requirements:
        _method:  POST
    defaults: {_controller: DatacityPrivateBundle:Applications:deleteuserapp}
    options:
        expose: true

