datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_adminusers:
    pattern:  /users
    defaults: { _controller: DatacityPrivateBundle:AdminUsers:index }

datacity_private_adminusers_remove:
    pattern:  /users/{usernameCanonical}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:AdminUsers:remove }
    options:
        expose: true

datacity_private_news:
    pattern:  /news
    defaults: { _controller: DatacityPrivateBundle:News:index }

datacity_private_news_add:
    pattern:  /news/add
    requirements:
        _method: GET|POST
    defaults: { _controller: DatacityPrivateBundle:News:add }

datacity_private_news_remove:
    pattern:  /news/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:News:remove }
    options:
        expose: true

datacity_private_partials:
    pattern:  /partials
    requirements:
        _method:  GET
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'DatacityPrivateBundle:Partials:appTemplate.html.twig'
    options:
        expose: true

datacity_private_modals:
    pattern: /modals/{pageName}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:Default:modals }

datacity_private_dataset_delete:
    pattern: /dataset/{id}
    requirements:
        _method:  DELETE
    defaults: { _controller: DatacityPrivateBundle:DataSet:delete }

datacity_private_dataset_save:
    pattern: /dataset/
    requirements:
        _method:  POST
    defaults: { _controller: DatacityPrivateBundle:DataSet:save }
    options:
        expose: true

datacity_private_dataset_get:
    pattern: /dataset/{slug}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }

datacity_private_source_post:
    pattern: /dataset/{slug}/source/
    requirements:
        _method: POST
    defaults: { _controller: DatacityPrivateBundle:Source:save }
    options:
        expose: true

datacity_private_user_get:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:User:get }
    requirements:
        _method:  GET
    options:
        expose: true

datacity_private_user_post:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:User:post }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_user_uploadimage:
    pattern: /user/uploadimage
    defaults: { _controller: DatacityPrivateBundle:User:uploadimage }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_user_updatepassword:
    pattern: /user/changepassword
    defaults: { _controller: DatacityPrivateBundle:User:updatepassword }
    requirements:
        _method:  POST
    options:
        expose: true