datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_dashboard:
    pattern:  /dashboard
    defaults: { _controller: DatacityPrivateBundle:Dashboard:index }
    
datacity_private_usersmanager:
    pattern:  /usersmanager
    defaults: { _controller: DatacityPrivateBundle:UsersManager:index }

datacity_private_usersmanager_remove:
    pattern:  /usersmanager/remove/{user_id}
    defaults: { _controller: DatacityPrivateBundle:UsersManager:remove, user_id: -1 }

datacity_private_newsmanager:
    pattern:  /newsmanager
    defaults: { _controller: DatacityPrivateBundle:NewsManager:index }

datacity_private_newsmanager_add:
    pattern:  /newsmanager/add
    defaults: { _controller: DatacityPrivateBundle:NewsManager:add}