datacity_private_homepage:
    pattern:  /
    defaults: { _controller: DatacityPrivateBundle:Default:index }

datacity_private_adminusers:
    pattern:  /admin/users
    defaults: { _controller: DatacityPrivateBundle:AdminUsers:index }

datacity_private_adminusers_remove:
    pattern:  /admin/users/{usernameCanonical}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:AdminUsers:remove }
    options:
        expose: true

datacity_private_adminusers_edit:
    pattern: /admin/users/{usernameCanonical}
    defaults: {_controller: DatacityPrivateBundle:AdminUsers:edit}
    options:
        expose: true

datacity_private_news:
    pattern:  /admin/news
    defaults: { _controller: DatacityPrivateBundle:News:index }

datacity_private_news_edit:
    pattern:  /admin/news/edit/{title}
    defaults: { _controller: DatacityPrivateBundle:News:edit }

datacity_private_news_add:
    pattern:  /admin/news/add
    requirements:
        _method: GET|POST
    defaults: { _controller: DatacityPrivateBundle:News:add }

datacity_private_news_remove:
    pattern:  /admin/news/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:News:remove }
    options:
        expose: true

datacity_private_partials:
    pattern:  /partials
    requirements:
        _method:  GET
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'DatacityPrivateBundle:Partials:appTemplate.html.twig'
    options:
        expose: true

datacity_private_modals:
    pattern: /modals/{pageName}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:Default:modals }

datacity_private_dataset_delete:
    pattern: /dataset/{slug}
    requirements:
        _method:  DELETE
    defaults: { _controller: DatacityPrivateBundle:DataSet:delete }

datacity_private_dataset_save:
    pattern: /dataset/{slug}
    requirements:
        _method:  PUT
    defaults: { _controller: DatacityPrivateBundle:DataSet:save }
    options:
        expose: true

datacity_private_dataset_add:
    pattern: /dataset/
    requirements:
        _method:  POST
    defaults: { _controller: DatacityPrivateBundle:DataSet:add }
    options:
        expose: true

datacity_private_dataset_get:
    pattern: /dataset/{offset}
    requirements:
        _method:  GET
        offset: \d+
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }
    options:
        expose: true

datacity_private_dataset_get:
    pattern: /dataset/{slug}
    requirements:
        _method:  GET
    defaults: { _controller: DatacityPrivateBundle:DataSet:get }

datacity_private_source_post:
    pattern: /dataset/{slug}/source/
    requirements:
        _method: POST
    defaults: { _controller: DatacityPrivateBundle:Source:save }
    options:
        expose: true

datacity_private_producers_get:
    pattern: /producers
    defaults: { _controller: DatacityPrivateBundle:Producers:get }
    requirements:
        _method:  GET
    options:
        expose: true

datacity_private_producers_edit:
    pattern: /admin/producers/edit/{name}
    defaults: {_controller: DatacityPrivateBundle:Producers:edit}
    options:
        expose: true

datacity_private_producer_remove:
    pattern:  /admin/producers/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:Producers:remove }
    options:
        expose: true

datacity_private_producers_post:
    pattern: /admin/producers/add
    defaults: { _controller: DatacityPrivateBundle:Producers:post }
    requirements:
        _method:  GET|POST

datacity_private_producers_list:
    pattern: /admin/producers/list
    defaults: { _controller: DatacityPrivateBundle:Producers:list }

datacity_private_user_get:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:User:get }
    requirements:
        _method:  GET
    options:
        expose: true

datacity_private_user_post:
    pattern: /user
    defaults: { _controller: DatacityPrivateBundle:User:post }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_user_uploadimage:
    pattern: /user/uploadimage
    defaults: { _controller: DatacityPrivateBundle:User:uploadimage }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_user_updatepassword:
    pattern: /user/changepassword
    defaults: { _controller: DatacityPrivateBundle:User:updatepassword }
    requirements:
        _method:  POST
    options:
        expose: true

datacity_private_applications_list:
    pattern: /admin/applications/list
    defaults: {_controller: DatacityPrivateBundle:Applications:list}

datacity_private_applications_post:
    pattern: /admin/applications/add
    defaults: {_controller: DatacityPrivateBundle:Applications:post}

datacity_private_tickets_list:
    pattern: /admin/tickets
    defaults: {_controller: DatacityPrivateBundle:Tickets:index}

datacity_private_ticket_remove:
    pattern:  /admin/tickets/{title}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:Tickets:remove }
    options:
        expose: true

datacity_private_tickets_detail_admin:
    pattern: /admin/ticket/{slug}
    defaults: { _controller: DatacityPrivateBundle:Tickets:detail}

datacity_private_tickets_get_allusertickets:
    pattern: /usertickets
    defaults: {_controller: DatacityPrivateBundle:Tickets:getusertickets}
    options:
        expose: true

datacity_private_tickets_get_userticket:
    pattern: /userticket/{slug}
    requirements:
        _method: GET
    defaults: {_controller: DatacityPrivateBundle:Tickets:getuserticket}
    options:
        expose: true

datacity_private_tickets_reply_usertickets:
    pattern: /userticket/{slug}/reply
    requirements:
        _method: POST
    defaults: {_controller: DatacityPrivateBundle:Tickets:replyUserTicket}
    options:
        expose: true

datacity_private_tickets_create_usertickets:
    pattern: /usertickets/add
    requirements:
        _method: POST
    defaults: {_controller: DatacityPrivateBundle:Tickets:createusertickets}
    options:
        expose: true

datacity_private_applications_edit:
    pattern: /admin/applications/edit/{name}
    defaults: {_controller: DatacityPrivateBundle:Applications:edit}
    options:
        expose: true

datacity_private_applications_remove:
    pattern:  /admin/applications/{slug}
    requirements:
        _method: DELETE
    defaults: { _controller: DatacityPrivateBundle:Applications:remove }
    options:
        expose: true

datacity_private_applications_get_userapplications:
    pattern: /applications/userapps
    defaults: {_controller: DatacityPrivateBundle:Applications:getuserapplications}
    options:
        expose: true

datacity_private_applications_get_application:
    pattern: /application/edit/{slug}
    defaults: {_controller: DatacityPrivateBundle:Applications:getapp}
    options:
        expose: true

datacity_private_applications_get_app_data:
    pattern: /application/getappdata
    defaults: {_controller: DatacityPrivateBundle:Applications:getappdata}
    options:
        expose: true

datacity_private_applications_post_user_app:
    pattern: /application/postuserapp
    requirements:
        _method:  POST
    defaults: {_controller: DatacityPrivateBundle:Applications:postuserapp}
    options:
        expose: true

datacity_private_applications_delete_user_app:
    pattern: /application/deleteuserapp
    requirements:
        _method:  POST
    defaults: {_controller: DatacityPrivateBundle:Applications:deleteuserapp}
    options:
        expose: true

datacity_private_admin_newsletter:
    pattern: /admin/newsletter
    defaults: {_controller: DatacityPrivateBundle:Newsletters:list}

datacity_private_admin_newsletter_add:
    pattern: /admin/newsletter/add
    defaults: {_controller: DatacityPrivateBundle:Newsletters:add}

datacity_private_admin_newsletter_remove:
    pattern: /admin/newsletter/{slug}
    requirements:
        _method: DELETE
    defaults: {_controller: DatacityPrivateBundle:Newsletters:remove}
    options:
        expose: true

datacity_private_admin_newsletter_launch:
    pattern: /admin/newsletter/{slug}
    defaults: {_controller: DatacityPrivateBundle:Newsletters:launch}
