imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

bc_bootstrap:
    less_filter: lessphp
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        datacity_api_url: "%datacity_api_url%"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ DatacityPublicBundle, DatacityPrivateBundle ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        jpegtran:
            bin: %jpegtran_path%
            progressive: true
            optimize: true
            apply_to:   "\.jpg$"
    twig:
        functions:
            jpegtran: { output: img/*.jpg }
    assets:
        angularmods:
            inputs:
                - %kernel.root_dir%/../vendor/angular-ui/ui-router/angular-ui-router.js
                - %kernel.root_dir%/../vendor/angularjs/angular-animate/angular-animate.js
                - %kernel.root_dir%/../vendor/angularjs/angular-sanitize/angular-sanitize.js
            output: js/angular-mods.js
        angularjs:
            inputs:
                - %kernel.root_dir%/../vendor/angularjs/angular/angular.js
            output: js/angular.js
        angularstrap:
            inputs:
                - %kernel.root_dir%/../vendor/mgcrea/angular-strap/angular-strap.js
                - %kernel.root_dir%/../vendor/mgcrea/angular-strap-tpl/angular-strap.tpl.js
            output: js/angular-strap.js
        angularstrapcss:
            inputs:
                - %kernel.root_dir%/../vendor/mgcrea/angular-motion/angular-motion.css
                - %kernel.root_dir%/../vendor/mgcrea/bootstrap-additions/bootstrap-additions.css
            output: css/angular-strap-dep.css
        angularnggrid: 
            inputs: 
            - %kernel.root_dir%/../vendor/angular-ui/ng-grid-script/ng-grid.js
            output: js/ng-grid.js
        angularnggridcss:
            inputs:
                - %kernel.root_dir%/../vendor/angular-ui/ng-grid-style/ng-grid.css
            output: css/ng-grid.css
        datasetsearchmod:
            inputs:
                - %kernel.root_dir%/../vendor/angular-ui/ui-bootstrap/ui-bootstrap-tpls-0.8.0.js
                - %kernel.root_dir%/../vendor/isteven/angular-multi-select/angular-multi-select.js
                - %kernel.root_dir%/../vendor/chieffancypants/angular-loading-bar/loading-bar.js
            output: js/datasetsearchmod.js
        datasetsearchmodcss:
            inputs:
                - %kernel.root_dir%/../vendor/isteven/angular-multi-select-style/angular-multi-select.css
                - %kernel.root_dir%/../vendor/chieffancypants/angular-loading-bar-style/loading-bar.css
            output: css/datasetsearchmod.css

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            string_functions:
                soundex: Datacity\PublicBundle\DQL\SoundexFunction


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Datacity\UserBundle\Entity\User
    registration:
        form:
            type: datacity_user_registration

jms_i18n_routing:
    default_locale: %locale%
    locales: [en, fr]
    strategy: prefix_except_default

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            blameable: true
            sluggable: true
            uploadable: true

jms_serializer:
    metadata:
        directories:
            - { path: %kernel.root_dir%/Resources/FOSUserBundle/serializer, namespace_prefix: 'FOS\UserBundle' }
