datacity_user:
    resource: "@DatacityUserBundle/Resources/config/routing.yml"
    prefix:   /

datacity_private:
    resource: "@DatacityPrivateBundle/Resources/config/routing.yml"
    prefix:   /private

datacity_public:
    resource: "@DatacityPublicBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
