security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        datacity_user:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: datacity_user
                csrf_provider: form.csrf_provider
                failure_path: fos_user_security_login
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                post_only: true
                default_target_path: datacity_public_homepage
            logout:
                path: fos_user_security_logout
                target: datacity_public_homepage
            anonymous:    true

    access_control:
        - { path: ^/(fr|en)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(fr|en)/private/admin/, role: ROLE_ADMIN }
        - { path: ^/private/admin/, role: ROLE_ADMIN }
        - { path: ^/(fr|en)/private/, role: ROLE_USER }
        - { path: ^/private/, role: ROLE_USER }